// M2 finding — replayLive's queue/in-flight bookkeeping was O(n) per operation (array splice
// in sortedInsert, indexOf scans in dropHop/takeInFlight), making a full replay superlinear
// in log size instead of the O(events) the surrounding code comments claim. Fixed by swapping
// the splice-based queue and the per-node in-flight list for binary min-heaps (src/run-live.js).
//
// This file is the correctness oracle for that change: test/fixtures/live-replay-20k.json was
// generated by running the OLD (pre-fix, array/indexOf-based) replayLive against a large
// deterministic synthetic log — see the generator script recreated below in
// `buildSpec`/`buildLog`, which must stay byte-for-byte the same shape as what produced the
// fixture. If this test ever needs a new fixture, regenerate it from the pre-fix
// implementation, not from the current one (that would defeat the point).
//
// No timing/duration assertions here (flaky) — see test/run-live-transport.test.js and this
// workstream's notes for the manual before/after benchmark numbers.

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { replayLive } from "../src/run-live.js";

const fixturePath = fileURLToPath(new URL("./fixtures/live-replay-20k.json", import.meta.url));
const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

function buildSpec(chainLen) {
  const nodes = [];
  const edges = [];
  for (let i = 0; i < chainLen; i++) nodes.push({ id: `n${i}`, data: i % 7 === 0 ? { duration: "1s" } : undefined });
  for (let i = 0; i < chainLen - 1; i++) edges.push({ id: `e${i}`, source: `n${i}`, target: `n${i + 1}` });
  return { nodes, edges };
}

function buildLog(chainLen, targetEvents) {
  const events = [];
  let t = 0;
  let i = 0;
  while (events.length < targetEvents) {
    const id = `n${i % chainLen}`;
    events.push({ t, type: "start", id });
    t += 1;
    if (i % 5 === 0) events.push({ t, type: "finish", id, n: 1 });
    else events.push({ t, type: "finish", id });
    t += 1;
    i++;
  }
  return events;
}

test("replayLive: heap-based queue/in-flight tracking matches the old array/indexOf implementation over a 20k-event log", () => {
  const spec = buildSpec(fixture.chainLen);
  const events = buildLog(fixture.chainLen, fixture.nEvents);
  const opts = { hopMs: fixture.hopMs };

  const mid = replayLive(spec, events, fixture.midT, opts);
  assert.deepEqual(mid, fixture.mid);

  const final = replayLive(spec, events, fixture.finalT, opts);
  assert.deepEqual(final, fixture.final);
  assert.equal(final.done, true);
});

test("replayLive: a 20k-event replay completes (no MAX_STEPS truncation, no throw)", () => {
  const spec = buildSpec(fixture.chainLen);
  const events = buildLog(fixture.chainLen, fixture.nEvents);
  const st = replayLive(spec, events, fixture.finalT, { hopMs: fixture.hopMs });
  assert.equal(st.done, true);
  // every node in the chain reached done — the replay walked the whole log, not a truncated prefix
  for (let i = 0; i < fixture.chainLen; i++) assert.equal(st.nodes[`n${i}`].status, "done");
});
